language: ruby
rvm:
  - 2.3.1
sudo: required
dist: precise
addons:
  postgresql: "9.5"
services:
  - postgresql
install:
  - bundle install
  - nvm install 8.9.4
  - node -v
  - npm i -g yarn
  - yarn
  - bundle exec rails webpacker:compile
script: bundle exec rails db:create db:schema:load db:migrate test spec