language: ruby
rvm:
  - 2.6.6
sudo: required
dist: precise
addons:
  postgresql: 9.5
services:
  - postgresql
install:
  - bundle install
script:
  - bundle exec rails db:create db:schema:load db:migrate RAILS_ENV=test
  - rspec
