version: '2'
services:
  app:
    container_name: pc_web
    build: .
    #command: rails server -p 3000 -b '0.0.0.0'
    command: foreman start -f Procfile.dev
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
      - "3035:3035"
    links:
      - postgres
    environment:
      - NODE_ENV=development
      - DOCKERIZED=true
    env_file:
      - ".env"
    tty: true
    stdin_open: true
  postgres:
    container_name: pc_postgres
    image: postgres:9.5
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  postgres-data:
