version: '3.0'
services:

  app:
    build: .
    command: bash -c "rm -f /app/tmp/pids/server.pid; rails s -b 'ssl://0.0.0.0:3001?key=localhost.key&cert=localhost.crt'"
    ## Uncomment next to use remote debugging
    # command: >
    #   bash -c "rm -f /app/tmp/pids/server.pid;
    #     bundle exec rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- /app/bin/rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app:cached
    ports:
      - 3001:3001
      - 1234:1234
      - 26162:26162
    depends_on:
      - postgres
    environment:
      - RAILS_ENV=development
      - DOCKERIZED=true
    env_file:
      - '.env'
    tty: true
    stdin_open: true

  postgres:
    image: postgres:9.5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=projectcredo_development
      - POSTGRES_PASSWORD=secret

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

volumes:
  postgres-data:
