
# The list of paper URLs prefixes
paper_urls:
  - https://www.ncbi.nlm.nih.gov/pubmed/
  - https://onlinelibrary.wiley.com/doi/
  - https://www.sciencedirect.com/science/article/
  - https://www.ncbi.nlm.nih.gov/pmc/articles/
  - https://academic.oup.com/edrv/article/
